---

- name: php nginx config directory
  file: >
    path=/etc/nginx
    state=directory
    owner=root
    group=root
    mode=0755
  sudo: yes

- name: php nginx config
  template: >
    src=nginx.j2
    dest=/etc/nginx/php_params
  notify:
    - nginx restart
  sudo: yes
