---

- name: package dependencies
  apt: >
    name={{ item }}
    state=present
  with_items:
    - libmysqlclient18
    - libpng12-0
    - libjpeg8
    - libfreetype6
    - libgd2-xpm
    - libxpm4
  sudo: yes

- name: package copy
  copy: >
    src=php_5.2.17-1+elao2_amd64.deb
    dest=/opt/php_5.2.17-1+elao2_amd64.deb
  sudo: yes

- name: package install
  apt: >
    deb=/opt/php_5.2.17-1+elao2_amd64.deb
  sudo: yes
