---

- name: package copy
  copy: >
    src=php_5.2.17-1+elao1_amd64.deb
    dest=/opt/php_5.2.17-1+elao1_amd64.deb
  sudo: yes

- name: package install
  apt: >
    deb=/opt/php_5.2.17-1+elao1_amd64.deb
  sudo: yes

- name: config - dist
  template: >
    src=php.ini-dist.j2
    dest=/usr/local/etc/php.ini
  notify:
    - php restart
  when: elao_env != 'prod'
  sudo: yes

- name: config - recommended
  template: >
    src=php.ini-recommended
    dest=/usr/local/etc/php.ini
  notify:
    - php restart
  when: elao_env == 'prod'
  sudo: yes

- name: service
  service: >
    name=php-fpm
    state=started
    enabled=true
  sudo: yes
